name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-qemu-action@v2

      - name: Ensure Docker Compose is available
        run: docker-compose version

      - name: Copy .env.example to .env
        run: cp ./Testing/IntegrationTesting/.env.example ./Testing/IntegrationTesting/.env

      - name: Make integration script executable
        run: chmod +x ./Testing/IntegrationTesting/scripts/run-integration.sh

      - name: Run integration script
        run: cd Testing/IntegrationTesting && npm run test:integration
